licencia

diff --git a/tor-chroot b/tor-chroot
--- a/tor-chroot
+++ b/tor-chroot
@@ -1,4 +1,10 @@
 #!/bin/bash
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
+if [[ $USER != root ]]; then
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
+fi
 export TORCHROOT=/opt/torchroot
 apt-get update
 apt-get -y install tor
